# Generated by Django 3.2.4 on 2021-10-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='articles', to='blog.Category'),
        ),
    ]
