# Generated by Django 3.2.4 on 2021-09-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='mostafa', max_length=50, verbose_name='گردآوری شده توسط'),
            preserve_default=False,
        ),
    ]
