# Generated by Django 3.2.4 on 2021-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام دسته بندی')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('publish', models.BooleanField(verbose_name='منتشر شود؟')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish', 'status'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
